export const IoCTokens = {
  LeadRepository: Symbol("LeadRepository"),
  EventBus: Symbol("EventBus"),
  Clock: Symbol("Clock"),
  IdGenerator: Symbol("IdGenerator"),
  AgentGateway: Symbol("AgentGateway"),
  HistoricalOutcomesRead: Symbol("HistoricalOutcomesRead"),
  SequenceLibrary: Symbol("SequenceLibrary"),
  StrategyPerformance: Symbol("StrategyPerformance"),
  ExperimentAssignment: Symbol("ExperimentAssignment"),
  StrategyPlanner: Symbol("StrategyPlanner"),
  PipelineReadModel: Symbol("PipelineReadModel"),
  DeadLetterQueue: Symbol("DeadLetterQueue"),
  Observability: Symbol("Observability"),
  TenantOpsMetrics: Symbol("TenantOpsMetrics"),
  WorkspaceRepository: Symbol("WorkspaceRepository"),
  WorkspaceConfig: Symbol("WorkspaceConfig"),
  ProvisioningJob: Symbol("ProvisioningJob"),
  TenantRepository: Symbol("TenantRepository"),
  CreateWorkspaceUseCase: Symbol("CreateWorkspaceUseCase"),
  EmailDelivery: Symbol("EmailDelivery"),
  Calendar: Symbol("Calendar"),
  OrchestrateLeadLifecycleUseCase: Symbol("OrchestrateLeadLifecycleUseCase"),
  ExecuteOutreachBookingLoopUseCase: Symbol("ExecuteOutreachBookingLoopUseCase"),
  CreateLead: Symbol("CreateLead"),
  Idempotency: Symbol("Idempotency"),
  ConfidenceGate: Symbol("ConfidenceGate"),
  HumanApproval: Symbol("HumanApproval"),
  Interpreter: Symbol("Interpreter"),
  Booking: Symbol("Booking"),
  InteractionTracker: Symbol("InteractionTracker"),
  Policy: Symbol("Policy"),
  Learning: Symbol("Learning"),
  Kpi: Symbol("Kpi"),
  Decisions: Symbol("Decisions"),
  TemplateLibrary: Symbol("TemplateLibrary"),
  TemplatePerformance: Symbol("TemplatePerformance"),
  MessageComposer: Symbol("MessageComposer"),
  SendTiming: Symbol("SendTiming"),
} as const;

export type IoCToken = (typeof IoCTokens)[keyof typeof IoCTokens];
